-- Migration: Seed initial official community form templates directly into the database
-- Ensures real database records exist without client-side mock fakes.

INSERT INTO public.community_form_templates (
  id,
  clinic_id,
  user_id,
  author_name,
  clinic_name,
  title,
  description,
  category,
  tags,
  schema,
  kind,
  is_published,
  is_featured,
  imports_count,
  likes_count,
  created_at,
  updated_at
)
VALUES
  (
    'a1000000-0000-0000-0000-000000000001',
    NULL,
    '00000000-0000-0000-0000-000000000000',
    'Equipe Pluri-Health',
    'Comunidade Oficial',
    'Anamnese Psicológica Adulto (TCC e Humanista)',
    'Estrutura abrangente para primeira consulta psicológica. Inclui histórico da queixa, rede de apoio, histórico familiar e metas terapêuticas.',
    'Psicologia',
    ARRAY['adulto', 'tcc', 'primeira-consulta', 'humanista'],
    '[
      {"id": "sec_motivo", "label": "1. Motivo da Consulta e Queixa Atual", "type": "section", "helpText": "Levantamento detalhado do motivo da busca por atendimento."},
      {"id": "campo_queixa_detalhada", "label": "Descrição da queixa principal e início dos sintomas", "type": "long_text", "required": true, "groupKey": "sec_motivo"},
      {"id": "campo_gatilhos", "label": "Gatilhos ou fatores que intensificam o sofrimento", "type": "long_text", "groupKey": "sec_motivo"},
      {"id": "campo_tentativas_anteriores", "label": "Tratamentos ou psicoterapias anteriores", "type": "checklist", "groupKey": "sec_motivo", "options": [{"id": "opt_psicoterapia", "label": "Psicoterapia prévia", "row": 0}, {"id": "opt_psiquiatria", "label": "Acompanhamento psiquiátrico", "row": 0}, {"id": "opt_medicacao", "label": "Uso contínuo de medicação", "row": 1}, {"id": "opt_nenhuma", "label": "Primeira vez em acompanhamento", "row": 1}]},
      {"id": "sec_historico_pessoal", "label": "2. Histórico Pessoal e Rotina", "type": "section"},
      {"id": "campo_rotina_sono", "label": "Qualidade do sono e alimentação", "type": "select", "groupKey": "sec_historico_pessoal", "options": [{"id": "sono_otimo", "label": "Regular e reparador"}, {"id": "sono_insonia", "label": "Insônia inicial/intermediária"}, {"id": "sono_hipersonia", "label": "Sonolência excessiva diurna"}, {"id": "sono_irregular", "label": "Horários muito desregulados"}]},
      {"id": "campo_humor_escala", "label": "Nível médio de ansiedade/estresse percebido (0 a 10)", "type": "slider", "min": 0, "max": 10, "sliderMinLabel": "Muito calmo", "sliderMaxLabel": "Altíssima ansiedade", "groupKey": "sec_historico_pessoal"},
      {"id": "campo_metas", "label": "Objetivos e expectativas com o processo terapêutico", "type": "long_text", "groupKey": "sec_historico_pessoal"}
    ]'::jsonb,
    'template',
    true,
    true,
    0,
    0,
    now(),
    now()
  ),
  (
    'a1000000-0000-0000-0000-000000000002',
    NULL,
    '00000000-0000-0000-0000-000000000000',
    'Dra. Camila Rocha',
    'Fisio & Movimento',
    'Avaliação Fisioterapêutica e Músculo-Esquelética',
    'Ficha clínica completa para fisioterapia ortopédica, desportiva e postural com escala EVA de dor e mapeamento articular.',
    'Fisioterapia',
    ARRAY['ortopedia', 'dor', 'postura', 'eva', 'articular'],
    '[
      {"id": "sec_dor_avalia", "label": "1. Mapeamento da Dor e Queixa Ortopédica", "type": "section"},
      {"id": "campo_localizacao_dor", "label": "Localização anatômica principal da dor", "type": "short_text", "required": true, "groupKey": "sec_dor_avalia"},
      {"id": "campo_tipo_dor", "label": "Tipo de dor relatada", "type": "multiple_choice", "groupKey": "sec_dor_avalia", "options": [{"id": "dor_queimacao", "label": "Queimação"}, {"id": "dor_pontada", "label": "Pontada / Fisgada"}, {"id": "dor_peso", "label": "Peso / Cansaço"}, {"id": "dor_pulsatil", "label": "Pulsátil"}]},
      {"id": "campo_eva_dor", "label": "Escala Visual Analógica (EVA) da dor no repouso", "type": "slider", "min": 0, "max": 10, "sliderMinLabel": "Sem dor (0)", "sliderMaxLabel": "Dor insuportável (10)", "groupKey": "sec_dor_avalia"},
      {"id": "sec_exame_fisico", "label": "2. Exame Físico e Amplitude de Movimento (ADM)", "type": "section"},
      {"id": "campo_inspecao_palpacao", "label": "Achados de palpação (tônus, edemas, pontos gatilho)", "type": "long_text", "groupKey": "sec_exame_fisico"},
      {"id": "campo_adm_tabela", "label": "Tabela de Amplitude de Movimento", "type": "table", "groupKey": "sec_exame_fisico", "options": [{"id": "col_articulacao", "label": "Articulação / Movimento"}, {"id": "col_graus", "label": "ADM Ativa (graus)"}, {"id": "col_dor", "label": "Presença de dor?"}]}
    ]'::jsonb,
    'template',
    true,
    true,
    0,
    0,
    now(),
    now()
  ),
  (
    'a1000000-0000-0000-0000-000000000003',
    NULL,
    '00000000-0000-0000-0000-000000000000',
    'Espaço Voz & Som',
    'Clínica Integrada',
    'Anamnese Fonoaudiológica Infantil (Fala e Linguagem)',
    'Avaliação do desenvolvimento de linguagem, mastigação, respiração e marcos do desenvolvimento comunicativo.',
    'Fonoaudiologia',
    ARRAY['infantil', 'linguagem', 'fala', 'mastigacao', 'marcos'],
    '[
      {"id": "sec_desenvolvimento", "label": "1. Marcos do Desenvolvimento da Linguagem", "type": "section"},
      {"id": "campo_primeiras_palavras", "label": "Idade das primeiras palavras / balbucio", "type": "short_text", "groupKey": "sec_desenvolvimento"},
      {"id": "campo_compreensao_fala", "label": "Compreensão de ordens simples e comunicação social", "type": "long_text", "groupKey": "sec_desenvolvimento"},
      {"id": "sec_motricidade_orofacial", "label": "2. Hábitos Orais e Mastigação", "type": "section"},
      {"id": "campo_habitos_orais", "label": "Hábitos deletérios observados", "type": "checklist", "groupKey": "sec_motricidade_orofacial", "options": [{"id": "chupeta", "label": "Uso de chupeta prolongado"}, {"id": "mamadeira", "label": "Uso de mamadeira"}, {"id": "respiracao_oral", "label": "Respiração predominantemente oral"}, {"id": "bruxismo", "label": "Apertamento / Bruxismo"}]}
    ]'::jsonb,
    'template',
    true,
    true,
    0,
    0,
    now(),
    now()
  ),
  (
    'a1000000-0000-0000-0000-000000000004',
    NULL,
    '00000000-0000-0000-0000-000000000000',
    'Gabriel Martins, TO',
    'Clínica Autonomia & Vida',
    'Terapia Ocupacional - Perfil de Desempenho Ocupacional',
    'Investigação minuciosa de Atividades de Vida Diária (AVDs), integração sensorial, rotina ocupacional e nível de independência funcional.',
    'Terapia Ocupacional',
    ARRAY['avds', 'autonomia', 'rotina', 'sensorial', 'to'],
    '[
      {"id": "sec_avds", "label": "1. Atividades de Vida Diária (AVDs)", "type": "section"},
      {"id": "campo_avd_alimentacao", "label": "Independência na alimentação e higiene pessoal", "type": "select", "groupKey": "sec_avds", "options": [{"id": "independente", "label": "Totalmente Independente"}, {"id": "supervisao", "label": "Necessita de Supervisão verbal"}, {"id": "ajuda_parcial", "label": "Ajuda física parcial"}, {"id": "dependente", "label": "Totalmente dependente"}]},
      {"id": "campo_rotina_diaria", "label": "Estrutura e previsibilidade da rotina semanal", "type": "long_text", "groupKey": "sec_avds"},
      {"id": "sec_sensorial", "label": "2. Perfil e Resposta Sensorial", "type": "section"},
      {"id": "campo_hipersensibilidade", "label": "Reações a estímulos sensoriais (tátil, auditivo, vestibular)", "type": "long_text", "groupKey": "sec_sensorial"}
    ]'::jsonb,
    'template',
    true,
    true,
    0,
    0,
    now(),
    now()
  ),
  (
    'a1000000-0000-0000-0000-000000000005',
    NULL,
    '00000000-0000-0000-0000-000000000000',
    'Dra. Mariana Prado',
    'NutriClin Saúde',
    'Anamnese Nutricional Clínica e Comportamental',
    'Rastreamento de hábitos alimentares, recordatório 24h simplificado, alergias, aversões e histórico de exames laboratoriais.',
    'Nutrição',
    ARRAY['nutricao', 'recordatorio', 'habitos', 'alimentacao', 'dietetica'],
    '[
      {"id": "sec_habitos_nutri", "label": "1. Hábitos e Histórico Alimentar", "type": "section"},
      {"id": "campo_ingestao_agua", "label": "Consumo médio diário de água (litros)", "type": "number", "groupKey": "sec_habitos_nutri"},
      {"id": "campo_restricoes_alergias", "label": "Alergias, intolerâncias ou aversões alimentares", "type": "long_text", "groupKey": "sec_habitos_nutri"},
      {"id": "campo_refeicoes_rotina", "label": "Número habitual de refeições por dia", "type": "select", "groupKey": "sec_habitos_nutri", "options": [{"id": "ref_1_2", "label": "1 a 2 refeições"}, {"id": "ref_3_4", "label": "3 a 4 refeições"}, {"id": "ref_5_mais", "label": "5 ou mais refeições"}, {"id": "ref_belisca", "label": "Belisca ao longo do dia sem horário fixo"}]},
      {"id": "sec_objetivos_nutri", "label": "2. Objetivos Nutricionais", "type": "section"},
      {"id": "campo_objetivo_principal", "label": "Meta principal (ex: emagrecimento, hipertrofia, controle glicêmico)", "type": "short_text", "required": true, "groupKey": "sec_objetivos_nutri"}
    ]'::jsonb,
    'template',
    true,
    true,
    0,
    0,
    now(),
    now()
  )
ON CONFLICT (id) DO NOTHING;
